#!/bin/bash
clear
# set -x
###
#
# Host Flash™ 3.1.2
#
# Downloads hosts file rules from various sources.
# Installs hosts file rules into /etc/hosts
# Integrates Host Flash™ hosts file rules with rules that already exist in /etc/hosts
#
# For OS: Linux (Debian)
# Tested With: Ubuntu flavours
#
# Lead Author: Lee Hodson
# Donate: https://paypal.me/vr51
# Website: https://host-flash.com<https://host-flash.com>
# This Release: 17th Nov 2018
# First Written: 18th Oct. 2015
# First Release: 2nd Nov. 2015
#
# Copyright Host Flash™ https://host-flash.com<https://host-flash.com>
# License: GPL3
#
# Programmer: Lee Hodson<journalxtra.com>, VR51<vr51.com>
#
# Use of this program is at your own risk
#
# INSTALLS OR UPDATES
#
# Use Host Flash™ to block access to websites (hosts), ad servers, malicious websites and time wasting websites.
# Use Host Flash™ to manage your hosts file
#
# TO RUN:
#
# Ensure the script is executable:
#
#  Right-click > properties > Executable
#
#  OR
#
#  chmod u+x hostflash
#
# Launch by clicking the script file or by typing `bash hostflash` at the command line.
#
# Host Flash™ will attempt to preserve existing host rules.
#
#
###

##
#
# TO DO / DEV NOTES
#
##
# versions: add deb installer
#  installed has desktop icon (like ServUp)
#
#  En/disable Automatic list update
#  En/disable Automatic script update
#
# CLI: disable HF, enable HF, add rule, remove rule, update lists, set options
#
#
# Build Options
#  Build pure list. No whitelisting
#   Check whitelists (extracted, found, not found)
#    Rebuild whitelists after check
#  Build filtered list. Whitelisting done
#   Install after build
#   Do not install after build
# Compact local whitelists and local blacklists (all lower, sort -u)
# View/Edit local lists (nano, pico, cat)
#
#
# Switchlist
#  Temporarily disable and enable whitelist hosts
# Options
#  Check .hfremoved list # Script written and tested ready for insertion
#   Move items from .hfremoved to post processing blacklist
#   Move items from .hfremoved to Switch List
#
# Move even more actions into functions.
# Tidy up
# Add input checking
# Refine/add messages
#
# Improve menu system
#  What do you want to do? Manage Lists, Update hosts, Manage Custom Files, See Info
#   Do it
#  Clearer messages
#
# Summary info on main screen / maybe footer for all screens
#  Add more useful info
#  Include link to host-flash.com
#
# Info table
#  Details about the live hosts file
#   size
#   lines
#   timestamp
#  View all HF configs
#
#  Details about the built hosts file
#   size
#   lines
#   timestamp
#
#  Info about each list
#   Last update time
#
# Add last 7 updates log
#  ${log#[time]}
#  ${log#[size]}
#  ${log#[lines]}
#
# Add hosts file backup option
#
#
# Integrate with SaLi (?)
#
# Go through functions to state the output format
#
###

##
# NOTES
#
# Build Process
#
#  The host file work is done in $HOME/src/hostflash/tmp. This eventually builds hosts.txt
#  The final build of hosts.txt is moved to $HOME/src/hostflash/
#  __enable looks for $HOME/src/hostflash/hosts.txt which it moves to /etc/hosts
#
# Whitelist Processing
#
#  Whitelist wild is processed twice:
#   As a normal whitelist
#   As a wild whitelist
#  A period is added before the first character of the host name
#
##

##
#
# CONFIGS - should be no reason to manually change these
#
# Any of these can be overruled by adding each variable along with its new value into $HOME/.config/hostflash/.hfrc
#
##

# Do not Use trailing slashes in URLs, URIs or directory paths

package='Host Flash™' # Name of software installed by this installer
version='3.1.2 - 17th Nov 2018'
debug='0'

# Clear arrays

unset app conf dir file log list message rem menu select mode essentialpackages credits flush listc listcc listsc

# Declare arrays and types

declare -A app conf dir file list log message rem

declare -a menu # Menu options are set within __menu_main()
declare -a select # Menu options count
declare -a mode # Used for notices
declare -a essentialpackages # Packages to install to help the build process
declare -a credits # Hosts file credits
declare -a flush # DNS cache flush commands
declare -i listc listcc listsc # For list repository counts

# Remote Hosts

rem[gith]='https://github.com/VR51/host-flash' # Github home URL for this package.
rem[gitp]='https://github.com/VR51/host-flash.git' # Software source package git address
rem[tld]='https://data.iana.org/TLD/tlds-alpha-by-domain.txt' # Official list of valid TLDs

# Directories
#  These are created by dir[@] dump. Be careful when adding directories to this list

dir[src]="$HOME/src/hostflash" # Directory where the source code will be stored locally
dir[tmp]="${dir[src]}/tmp" # Directory where temporary files will be stored locally
dir[docs]="${dir[src]}/DOC" # Location of program documents. # To be written
dir[conf]="$HOME/.config/hostflash" # Location of custom configuration files.

# Files

# System hosts file location. Where it is copied from and where it is installed to.
# file[hosts]='/etc/hosts' # Location of system hosts file in Unix, Unix-like and POSIX systems.
# file[hosts]='/private/etc/hosts' # iOS, Apple Mac
# file[hosts]='/system/etc/hosts' # Android
# file[hosts]='%SystemRoot%\System32\drivers\etc\hosts' # Windows NT, 2000, XP,[5] 2003, Vista, 2008, 7, 2012, 8, 10

if test -f "/system/etc/hosts"; then
	file[hosts]='/system/etc/hosts'
elif test -f "/private/etc/hosts"; then
	file[hosts]='/private/etc/hosts'
elif test -f "/etc/hosts"; then
	file[hosts]='/etc/hosts'
else
	echo "Unable to detect the location of this system's hosts file."
	echo "Please edit the hostflash program at section around line 187 to set the value of ${bold}file[hosts]${normal} to point to your hosts file."
	echo "Press any key to exit $package"
	read a
	exit 1
fi

# HF Config Files
#  These are created by file[@] dump. Be careful when adding files to this list

file[conf]="${dir[conf]}/.hfrc" # Location of user's custom settings for Host Flash™.
file[confwl]="${dir[conf]}/.hfwlrc" # Location of the user's custom whitelist.
file[confwlw]="${dir[conf]}/.hfwlwrc" # Location of the user's custom whitelist-wild.
file[confbl]="${dir[conf]}/.hfblrc" # Location of the user's custom blacklist.
file[confcl]="${dir[conf]}/.hfclrc" # Location of the user's custom hosts lists.
file[confr]="${dir[conf]}/.hfremoved" # Hosts removed from hosts list during hosts build/update.
file[conftld]="${dir[conf]}/.hftld" # Location of valid TLD list.
file[debug]="${dir[conf]}/.debug.txt" # Location of debug logging file.

# to be used in a later version
file[confpost]="${dir[conf]}/.hfpost" # Location of the post processing blacklist (block hosts that are wild needlessly whitelisted)
file[confsl]="${dir[conf]}/.hfslrc" # Location of the user's hosts switch list.
file[log]="${dir[conf]}/.log" # Location of the log file.

# App Launcher Settings
# These are specific to the application/task manager installer (yet to be implemented)

app[icon]="${dir[src]}/data" # Directory where the application icon will be located.
app[bin]='/usr/bin' # Binary installation path. Where should the compiled binary be installed to? Exact path. # Not required for this installer.
app[icon]="hostflash.svg" # Icon name
app[type]='Application' # 
app[cats]='Utilities' # Application launcher categories
app[binary]="hostflash" # Name of the binary file that is this program.

# Detected settings

user=$(whoami) # Current User
group=$(id -g -n $user) # Current user's primary group


###
#
# DECLARE LIST ARRAYS
# 
###

# Declare custom list associative arrays. If they are not declared we cannot use them.

# Count Lists
listc=$(grep -E '\[status[[:digit:]]+]=' "$0" | wc -l) # Count lists in hostflash script
if test $(grep -En '\[status[[:digit:]]+]=' "${file[confcl]}")
then
	listcc=$(grep -E '\[status[[:digit:]]+]=' "${file[confcl]}" | wc -l) # Count custom lists in .hfclrc
else
	listcc=0
fi
let listsc=listc+listcc


##
#
# LISTS
#
#
# These are...
#
# list[status]='Enabled / Disabled' # + or - for TRUE or FALSE
# list[info]='List Domain' # The name of the list
# list[src]='Download URL' # From where the package will be retrieved
# list[file]='Download Package' # Name of package retrieved
# list[target]='Package Target' # Name of usable file in a retrieved zip package / Name of file created on retrieval if FLAG is raw
# list[flag]='Flags: E.g Package Type' # direct (the URL leads to the file), raw (URL + File name), unzip (URL + file name), p7zip (URL + File name).
#
# Changes to list[status] are stored in .hfrc
# Custom lists will be added to .hfclrc
#		Framework in place: conf etc... Needs menu section to be added.
#
##

# TO DO: Change to list[NUM TYPE]
#https://hosts-file.net/?s=Download
list[status1]='+'
list[info1]='hosts-file.net (Liberal: Blocks mostly adware, spyware, malware and trackers. Big list)'
list[src1]='http://hosts-file.net/download'
list[file1]='hosts.txt'
list[target1]='hosts.txt'
list[flag1]='raw'

list[status2]='+'
list[info2]='hosts-file.net update (Liberal: Blocks mostly adware, spyware, malware and trackers. Big list)'
list[src2]='http://hosts-file.net'
list[file2]='hphosts-partial.txt'
list[target2]='hosts.txt'
list[flag2]='raw'

list[status3]='+'
list[info3]='mvps.org (Liberal: Blocks mostly adware, spyware, malware and trackers. Big list)'
list[src3]='http://winhelp2002.mvps.org'
list[file3]='hosts.zip'
list[target3]='HOSTS'
list[flag3]='unzip'

list[status4]='+'
list[info4]='free.fr-Trackers (Moderate: Blocks trackers)'
list[src4]='http://rlwpx.free.fr/WPFF'
list[file4]='htrc.7z'
list[target4]='Hosts.trc'
list[flag4]='p7zip'

list[status5]='+'
list[info5]='free.fr-Ad-Servers (Moderate: Blocks ad servers)'
list[src5]='http://rlwpx.free.fr/WPFF'
list[file5]='hpub.7z'
list[target5]='Hosts.pub'
list[flag5]='p7zip'

list[status6]='+'
list[info6]='free.fr-Malware (Moderate: Blocks malware domains)'
list[src6]='http://rlwpx.free.fr/WPFF'
list[file6]='hrsk.7z'
list[target6]='Hosts.rsk'
list[flag6]='p7zip'

list[status7]='+'
list[info7]='free.fr-Adult (Moderate: Blocks adult domains. Coincidentally blocks forums and some social sites)'
list[src7]='http://rlwpx.free.fr/WPFF'
list[file7]='hsex.7z'
list[target7]='Hosts.sex'
list[flag7]='p7zip'

list[status8]='+'
list[info8]='free.fr-Misc (Moderate: Blocks miscellaneous domains)'
list[src8]='http://rlwpx.free.fr/WPFF'
list[file8]='hmis.7z'
list[target8]='Hosts.mis'
list[flag8]='p7zip'

list[status9]='+'
list[info9]='someonewhocares.org (Liberal: Blocks mostly adware, spyware, malware and trackers. Small list)'
list[src9]='http://someonewhocares.org/hosts'
list[file9]='hosts'
list[target9]='hosts.txt'
list[flag9]='raw'

list[status10]='+'
list[info10]='malwaredomainlist.com (Liberal: Blocks mostly malware. Small list)'
list[src10]='http://www.malwaredomainlist.com/hostslist'
list[file10]='hosts.txt'
list[target10]='hosts.txt'
list[flag10]='raw'

list[status11]='+'
list[info11]='KADhosts (Liberal: Blocks malware hosts)'
list[src11]='https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt'
list[file11]='hosts.txt'
list[target11]='hosts.txt'
list[flag11]='direct'

list[status12]='+'
list[info12]='yoyo.org (Liberal: Blocks adservers)'
list[src12]='https://pgl.yoyo.org/as/serverlist.php?showintro=0;hostformat=hosts'
list[file12]='hosts.txt'
list[target12]='hosts.txt'
list[flag12]='direct'

list[status13]='+'
list[info13]='Mitchell Krog (Liberal: Blocks spam bot hosts)'
list[src13]='https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts'
list[file13]='hosts.txt'
list[target13]='hosts.txt'
list[flag13]='direct'

list[status14]='+'
list[info14]='CoinBlockerLists (Liberal: Blocks cryptominers)'
list[src14]='https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser'
list[file14]='hosts.txt'
list[target14]='hosts.txt'
list[flag14]='direct'

list[status15]='+'
list[info15]='Lightswitch05 (Liberal: Blocks ads and trackers)'
list[src15]='https://raw.githubusercontent.com/lightswitch05/hosts/master'
list[file15]='ads-and-tracking-extended.txt'
list[target15]='hosts.txt'
list[flag15]='raw'

list[status16]='+'
list[info16]='AdAway (Liberal: Blocks ad networks)'
list[src16]='https://adaway.org'
list[file16]='hosts.txt'
list[target16]='hosts.txt'
list[flag16]='raw'

list[status17]='+'
list[info17]='hostsfile.org (Very Strict: Regular blocks + porn, gambling and gaming sites)\n'
list[src17]='http://www.hostsfile.org/Downloads'
list[file17]='hosts.txt'
list[target17]='hosts.txt'
list[flag17]='raw'

# Others

list[status18]='+'
list[info18]='Community Whitelist (Host Flash™ whitelist. Unblocks a limited set of sites blocked by the other blacklists)'
list[src18]='https://gist.githubusercontent.com/VR51/7eaace2b6778ea508996/raw'
list[file18]='whitelist.txt'
list[target18]='whitelist.txt'
list[flag18]='direct'

list[status19]='+'
list[info19]='Community Whitelist Wild (Host Flash™ wild whitelist. Unblocks a limited set of sites blocked by the other blacklists)'
list[src19]='https://gist.githubusercontent.com/VR51/9798c78337fe2f7ad589/raw/'
list[file19]='whitelist-wild.txt'
list[target19]='whitelist-wild.txt'
list[flag19]='direct'

list[status20]='+'
list[info20]='Community Blacklist (Host Flash™ blacklist. Blocks a limited set of sites not blocked by other lists)'
list[src20]='https://gist.githubusercontent.com/VR51/ef3b90b1be2693a44f27/raw/'
list[file20]='blocklist.txt'
list[target20]='hosts.txt'
list[flag20]='direct'

list[status21]='+'
list[info21]='Local Whitelist (Your own custom whitelist)'
list[src21]='localhost'
list[file21]='.hfwlrc'
list[target21]='whitelist.txt'
list[flag21]='raw'

list[status22]='+'
list[info22]='Local Whitelist Wild (Your own custom wild whitelist)'
list[src22]='localhost'
list[file22]='.hfwlwrc'
list[target22]='whitelist-wild.txt'
list[flag22]='raw'

list[status23]='+'
list[info23]='Local blacklist (Your own custom blacklist)'
list[src23]='localhost'
list[file23]='.hfblrc'
list[target23]='hosts.txt'
list[flag23]='raw'



# GENERAL

essentialpackages=( zip unzip 7z curl sed git )
	
conf[ess]=0 # Essentials # Install build essential software. 0 = Not done, 1 = Done
conf[upv]=0 # Update Host Flash™ program.
#conf[locv]=$($binary -v) # Installed package version
conf[inst]=$( ls -l "$0" | cut -d' ' -f 6-8) # $package installation date
conf[locv]="$version installed ${conf[inst]}"
conf[gitv]=$(curl -v --silent "${rem[gith]}/commit/master" --stderr - | grep '<relative-time datetime' | sed -E 's#<relative-time datetime="(.+)">.+$#\1#g' | tr -d '[:space:]' | tr '[:alpha:]' ' ')
conf[hosts]=$( ls -l "${file[hosts]}" | cut -d' ' -f5 ) # Hosts file size
conf[hostt]=$( ls -l "${file[hosts]}" | cut -d' ' -f 6-9 ) # Hosts file timestamp
conf[hostc]=$( wc -l "${file[hosts]}" | cut -d' ' -f1 ) # Hosts file line count

conf[ip]='0.0.0.0' # Redirect IP address
conf[mode]='0' # Build Only or Build and Install 0 or 1

# LOGS
# Not yet used
function __log() {
	# @1 = Message
	
	message=$1
	
	now="$(date +"%Y-%m-%d %H:%M:%S")"
	log[$now]="$now: $message"
	
	# ${file[log]}
}

## END SETTINGS

## BEGIN 

# Other settings
bold=$(tput bold)
normal=$(tput sgr0)

# Locate where we are
filepath="$( echo $PWD )"

# A Little precaution
cd "$filepath"

# Make/Remove directories and files

function __download_tlds() {
	if test $(find "${file[conftld]}" -mmin +1440) || test ! -f "${file[conftld]}" # If exists but is older than 1440 minutes
	then
		curl -e "${rem[tld]}" "${rem[tld]}" -o "${file[conftld]}"
		sed -e 's/\(.*\)/\L\1/' "${file[conftld]}" > "${file[conftld]}tmp"
		grep -vE '^#' "${file[conftld]}tmp" > "${file[conftld]}"
		# Next lines allow the file to be passed to Grep as a string of ORs
		#grep -vE '^#' "${file[conftld]}tmp" | tr '[:space:]' '|' > "${file[conftld]}"
		#sed -i 's/[|]$//' "${file[conftld]}" # Remove superfluous | from end of file
		#rm "${file[conftld]}tmp"
	fi
}
__download_tlds # Get TLD list # Not yet used.


case "${debug}" in
	0)
		if test -d "${dir[tmp]}"; then
			rm -r "${dir[tmp]}" # Clean the tmp directory but not if we are debugging.
		fi
	;;
esac

mkdir -p "${dir[@]}" # Make directories
touch -a "${file[@]}" # Make config files


# INSTALL RC SETTINGS

function __repaint() {
# Loads configs then clears the screen
# Whatever calls this should reload the screen for the new configs to be reflected on the screen

	# @1 = type: soft, hard, conf, ret
	#  soft just refreshes the screen
	#  hard reloads the script in the current shell
	#  conf must be followed by a config file to load. Loads default conf then extra conf.
	#  'no argument' loads the default config file represented by ${file[conf]}
	# @2..@n = config file(s) to reload
	#
	# ret executes the function stated in $2
	#
	# We use $in instead of $@
	
	clear
	
	in=( $@ )
	
	case ${in[0]} in
	
		soft) # Reset variables
			tset
	
		;;
		
		hard) # Restart this script
			exec bash "$0"
		
		;;

		conf) # Include basic conf and any extras listed in $@

		if source "${in[1]}"
		then
				for i in ${in[@]:1}; do
					source "$i"
				done
				source "${file[conf]}"
		else
				for i in ${in[@]:1}; do
					. "$i"
				done
				. "${file[conf]}"
		fi
		
		;;
		
		ret)
			$2
		
		;;

		*) # Include basic conf only

		if source "${file[conf]}"
		then
				source "${file[conf]}"
		else
				. "${file[conf]}"
		fi
		
		;;
	
	esac

}


# Include custom lists

__repaint conf "${file[confcl]}"



##
# Actions
##


function __run() {
	# Check for terminal then run else just run program
	
	tty -s
	if test "$?" -ne 0 ; then
		__launch
	else
		__menu_main "$1" # This will be changed when CLI added
	fi

}

function __hosts_update() {
	# Read the file of hosts and remove any line listed in the input whitelist file
	# The results are logged in a file in the config directory.

	# @1 = type: (file) norm or wild, or (string) rem or remw
	# @2 = file to remove data from
	# @3 = file containing lines of data to remove from @2 or single line of text to remove from @2
	
	f2="$2"
	f3="$3"

	ip=$(echo "${conf[ip]}" | sed 's/\./[.]/g') # Convert periods to character group (just commenting out sometimes failed)
	
	case $1 in
		norm)
			# We tried a method that removed the while loop. It was overzealous so reverted back to while loop.
			echo -ne "\n###\n# NON-WILD WHITELIST\n###\n\n" >> "${file[confr]}"

			while read LINE ; do
				LINE=$(echo $LINE | sed 's/\./[.]/g')
				echo -ne  "\n# $LINE\n\n" >> "${file[confr]}"
				grep -i "^${ip}[[:blank:]]${LINE}"'$' "${f2}" >> "${file[confr]}" # List of hosts removed during whitelisting
				grep -vi "^${ip}[[:blank:]]${LINE}"'$' "${f2}" > "${f2}.tmp" # This method removes whitelisted hostnames
				mv -f "${f2}.tmp" "${f2}"
			done < "${f3}"

		;;

		wild)

			# Process wild whitelist to replace .TLD with all possible TLD values
			# Testing - will eventually allow for .TLD in wild whitelist to represent any valid TLD.
			# Disabled for now because it causes grep to crash while whitelisting -- too many arguments.
			#while read LINE ; do
			#	sed -r "s/^(.*)[.]TLD/\1.${LINE}/g" "$3" >> "${dir[tmp]}/wlwtmp" # Replace 'TLD' with list of possible TLDs
			#	echo '' >> "${dir[tmp]}/wlwtmp"
			#done < "${file[conftld]}"

			#grep -v "[.]TLD" "$3" >> "${dir[tmp]}/wlwtmp" # Add none .TLD$ lines back into the wild list

			echo -ne "\n###\n# WILD WHITELIST PASS 2 - WILD\n###\n\n" >> "${file[confr]}"

			while read LINE ; do
				LINE=$(echo $LINE | sed 's/\./[.]/g') # Replace periods with character group match to prevent periods being interpreted as 'any character'
				echo -ne  "\n# $LINE\n\n" >> "${file[confr]}"
				grep -i "^${ip}[[:blank:]].*[.]${LINE}" "${f2}" >> "${file[confr]}" # List of hosts removed during whitelisting
				grep -vi "^${ip}[[:blank:]].*[.]${LINE}" "${f2}" > "${f2}.tmp" # This method removes whitelisted hostnames
				mv -f "${f2}.tmp" "${f2}"
			done < "${f3}"

		;;

		linen) # Not yet used
		
			data=$3
			data=$(echo $data | sed 's/\./[.]/g') # Replace periods with character group to prevent them being interpreted as 'any character'
			# sed -r -i "s/${ip}[[:blank:]]$3.*?$//g" "$2" # Remove exact match
			grep -i "^${ip}[[:blank:]]${data}"'$' "$2" >> "${file[confr]}" # List of hosts removed during whitelisting
			grep -vi "^${ip}[[:blank:]]${data}"'$' "$2" > "$2.tmp" # This method removes whitelisted hostnames
			mv -f "$2.tmp" "$2"

		;;

		linew) # Not yet used
			data=$3
			data=$(echo $data | sed 's/\./[.]/g') # Replace periods with character group to prevent them being interpreted as 'any character'
			# sed -r -i "s/${ip}[[:blank:]].*\.$3.*?$//g" "$2" # Remove any line with a match
			grep -i "^${ip}[[:blank:]].*[.]${data}" "$2" >> "${file[confr]}" # List of hosts removed during whitelisting
			grep -vi "^${ip}[[:blank:]].*[.]${data}" "$2" > "$2.tmp" # This method removes whitelisted hostnames
			mv -f "$2.tmp" "$2"

		;;

	esac

}

function __conf_update() {
	# Add or remove a single host from the .hf*rc config files
	# ! Considered merging this function with __hosts_update. Opted to keep the two separate. It simplifies input sanitization (to come later).

	# @1 = type: add, rem or remw
	# @2 = data to add/remove
	# @3 = file to add/remove @1 to/from

	d=$2
	f=$3

	case $1 in

		add)
			grep "${d}" "${f}"
			if test $? -eq 1
			then
				echo "${d}" >> "${f}"
			fi
		;;

		rem)
			sed -r -i "s/${d}.*?$//g" "${f}" # Remove exact match
			sed -i '/^$/d' "${f}" # Remove empty lines
		;;

		remw)
			sed -r -i "s/.*?${d}.*?$//g" "${f}" # Remove any line with a match
			sed -i '/^$/d' "${f}" # Remove empty lines
		;;
	esac
	
}

function __conf_delete() {
	__repaint conf "${file[confcl]}"
	
	# Delete specified file
	# @1 = File to delete
	# @2 = File's friendly name

	f[1]=${1}
	f[2]=${2}

	printf "${bold}DELETE CONFIG FILES${normal}"
	printf "\n\nReset chosen configuration file\n\n"

	# Display menu
	unset menu
	menu[1]="Proceed: Reset ${f[2]} by deleting file ${f[1]}"
	menu[2]="Return: Do not reset ${f[2]}"

	m=1
	while [ $m -le ${#menu[@]} ] ; do
		printf "$m) ${menu[$m]}\n"
		print
		let m=m+1
	done
	
	printf "\nChoose an option then press Enter:\n"
	read a
	
	while true ; do
		case $a in
			1)
				if test -f "${f[1]}"; then
					rm "${f[1]}"
					printf "${f[2]} reset.\n"
					printf "\nPress any key to continue\n"
					touch "${f[1]}"
					read something
				else
					printf "${f[2]} custom settings not yet created. Nothing to do. Nothing done.\n"
					printf "\nPress any key to continue\n"
					read something
				fi
				__menu_reset_confs
			;;
			
			2)
				__menu_reset_confs
			;;
			
			*)
				__repaint
			;;
		esac
	done

}

function __status() {
	# Change status of list: On or Off.
	
	# @1 = host list to change status of
	
	n=$1
	if grep "list\[status${n}]='-'" "${file[conf]}"
	then
		sed -i "/list\[status${n}]=/d" "${file[conf]}"
		echo -e "list[status${n}]='+'" >> "${file[conf]}"
	else
		sed -i "/list\[status${n}]=/d" "${file[conf]}"
		echo -e "list[status${n}]='-'" >> "${file[conf]}"
	fi
	
}


function __build() {
	# Build the hosts file: download lists, clean them, merge them, create new hosts file

	# Download lists. Merge them into new hosts file
	n=1
	until [ $n -eq 0 ]; do

		status="${list[status${n}]}"
		info="${list[info${n}]}"
		src="${list[src${n}]}"
		file="${list[file${n}]}"
		target="${list[target${n}]}"
		flag="${list[flag${n}]}"

		if test "$status" = '+' # The list is enabled
		then

			if test "$src" != 'localhost'
			then
				# Download the lists
				if test "$flag" = 'direct' # $file is the target
				then
					curl -e "$src" "$src" -o "${dir[tmp]}/$target"
				fi

				if test "$flag" = 'raw'
				then
					curl -e "$src" "$src/$file" -o "${dir[tmp]}/$target"
				fi

				if test "$flag" = 'unzip' || test "$flag" = 'p7zip'
				then
					curl -e "$src" "$src/$file" -o "${dir[tmp]}/$file"
					# Extract package content
					if test "$flag" = 'unzip'; then unzip -o "${dir[tmp]}/$file" -d "${dir[tmp]}"; fi
					if test "$flag" = 'p7zip'; then 7z e -y "${dir[tmp]}/$file" -o"${dir[tmp]}" ; fi
					# Move target file
					cat "${dir[tmp]}/$target" >> "${dir[tmp]}/hosts-temp.txt"
				fi

				# Merge files

				if test "$target" = 'hosts.txt'
				then
					cat "${dir[tmp]}/$target" >> "${dir[tmp]}/hosts-temp.txt"
				fi

				if test "$target" = 'whitelist'
				then
					cat "${dir[tmp]}/$target" >> "${dir[tmp]}/whitelist-temp.txt"
				fi

				if test "$target" = 'whitelist-wild'
				then
					cat "${dir[tmp]}/$target" >> "${dir[tmp]}/whitelist-wild-temp.txt"
				fi

				# Clean up retrieved files

				if test -f "${dir[tmp]}/$file"
				then
					rm "${dir[tmp]}/$file"
				fi
				
				if test -f "${dir[tmp]}/$target"
				then
					rm "${dir[tmp]}/$target"
				fi

			else # It's local host
			
				if test "$target" = 'whitelist.txt'
				then
					cat "${dir[conf]}/$file" >> "${dir[tmp]}/whitelist-temp.txt"
				fi
				
				if test "$target" = 'whitelist-wild.txt'
				then
					cat "${dir[conf]}/$file" >> "${dir[tmp]}/whitelist-wild-temp.txt"
					
				if test "$target" = 'hosts.txt'
				then
					cat "${dir[conf]}/$file" >> "${dir[tmp]}/hosts-temp.txt"
				fi

			fi

			# Add empty line to end of temp files to prevent malformatting on merge. It is ok if these don't yet exist. They soon will.
			echo >> "${dir[tmp]}/whitelist-temp.txt"
			echo >> "${dir[tmp]}/whitelist-wild-temp.txt"
			echo >> "${dir[tmp]}/hosts-temp.txt"

			credits+=("# Includes hosts blacklist from $info\n")

		fi

		fi

		if test ${#status} -eq 0
		then
			let n=n-n
		else
			let n=n+1
		fi

	done

	__repaint

	printf "This next part could take some time.\nLook in ${dir[tmp]} to view activity in realtime.\n\nProcessing...\n"

	# Convert non-UTF8 characters to UTF8. Fix characters in French lists.
	# And remove empty lines from whitelists

	iconv -c -t UTF-8//TRANSLIT < "${dir[tmp]}/whitelist-temp.txt" > "${dir[tmp]}/whitelist-temp-copy.txt"
	sed '/^$/d' "${dir[tmp]}/whitelist-temp-copy.txt" > "${dir[tmp]}/whitelist-temp.txt"
	rm "${dir[tmp]}/whitelist-temp-copy.txt"

	iconv -c -t UTF-8//TRANSLIT < "${dir[tmp]}/whitelist-wild-temp.txt" > "${dir[tmp]}/whitelist-wild-temp-copy.txt"
	sed '/^$/d' "${dir[tmp]}/whitelist-wild-temp-copy.txt" > "${dir[tmp]}/whitelist-wild-temp.txt"
	rm "${dir[tmp]}/whitelist-wild-temp-copy.txt"

	iconv -c -t UTF-8//TRANSLIT < "${dir[tmp]}/hosts-temp.txt" > "${dir[tmp]}/hosts-temp-copy.txt"
	rm "${dir[tmp]}/hosts-temp.txt"

	#	Format raw list data in hosts-temp.txt

	grep -v '^#' "${dir[tmp]}/hosts-temp-copy.txt" > "${dir[tmp]}/hosts-temp.txt" # Remove all lines that begin with a comment
	sed -r -i 's/[[:blank:]]+/ /g' "${dir[tmp]}/hosts-temp-copy.txt" # Convert spaces and tabs each to a single space
	grep -Ev "[[:blank:]](ip6-)?(localhost|loopback|localnet|mcastprefix|allnodes|allrouters)\s?\b" "${dir[tmp]}/hosts-temp-copy.txt" > "${dir[tmp]}/hosts-temp.txt" # Remove localhost lines - the computer's installed host file already has localhost defined the way it should be
	grep -E '^[012][\.01-9]{1,2}' "${dir[tmp]}/hosts-temp.txt" > "${dir[tmp]}/hosts-temp-copy.txt" # Remove any line that does not begin with 0,1 or 2
	sed -r -i "s/^[012][\.01-9]{1,2}+[[:blank:]]/${conf[ip]} /g" "${dir[tmp]}/hosts-temp-copy.txt" # Replace with a single space and the new IP address everything up to, and including, the first tab in each line

	# Sort the lists
	if test -f "${dir[tmp]}/hosts-temp-copy.txt"
	then
		sed -i 's/\r$//' "${dir[tmp]}/hosts-temp-copy.txt" # Standardise line endings
		sort -f -u "${dir[tmp]}/hosts-temp-copy.txt" > "${dir[tmp]}/hosts-temp.txt"
		rm "${dir[tmp]}/hosts-temp-copy.txt"
	fi

	if test -f "${dir[tmp]}/whitelist-temp.txt"
	then
		sed -i 's/\r$//' "${dir[tmp]}/whitelist-temp.txt" # Fix line endings
		sort -f -u "${dir[tmp]}/whitelist-temp.txt" > "${dir[tmp]}/whitelist.txt"
		rm "${dir[tmp]}/whitelist-temp.txt"
	fi

	if test -f "${dir[tmp]}/whitelist-wild-temp.txt"
	then
		sed -i 's/\r$//' "${dir[tmp]}/whitelist-wild-temp.txt" # Fix line endings
		sort -f -u "${dir[tmp]}/whitelist-wild-temp.txt" > "${dir[tmp]}/whitelist-wild.txt"
		rm "${dir[tmp]}/whitelist-wild-temp.txt"
	fi

	# Process whitelist -- remove whitelisted domains from hosts-temp.txt
	# Always pass wild through norm too
	__hosts_update "norm" "${dir[tmp]}/hosts-temp.txt" "${dir[tmp]}/whitelist.txt"
	__hosts_update "norm" "${dir[tmp]}/hosts-temp.txt" "${dir[tmp]}/whitelist-wild.txt"
	__hosts_update "wild" "${dir[tmp]}/hosts-temp.txt" "${dir[tmp]}/whitelist-wild.txt"
	
	# hosts.txt should not exist at this point
	if test -f "${dir[tmp]}/hosts.txt"
	then
		rm "${dir[tmp]}/hosts.txt"
	fi

	#	Get head of the existing hosts file stored at /etc/hosts
	#	Remove old Host Flash™ blacklist from existing hosts file, assuming blacklist exists
	#	Remove empty lines from the end of the header
	#	This creates file hosts.head which is used a few lines down from here

	if grep -zPo '# Host.? Flash' "${file[hosts]}"
	then
		grep -zPo '(?s).*# Host.? Flash' "${file[hosts]}" | head -n -1 | grep -v '^[[:space:]]$' > "${dir[tmp]}/hosts.head" # Remove old HF data, remove HF header remove empty lines.
	fi

	printf '\n\n# Host Flash™ Firewall\n\n# Credits\n\n' >> "${dir[tmp]}/hosts.head" # Add HF heading

	for i in "${credits[@]}" ; do
		printf "$i" >> "${dir[tmp]}/hosts.head" # Add HF list provider credits
	done

	printf "\n\n# Installed with $package\n\n# Visit host-flash.com to learn more\n\n" >> "${dir[tmp]}/hosts.head" # Add HF credit

	cat "${dir[tmp]}/hosts.head" "${dir[tmp]}/hosts-temp.txt" > "${dir[src]}/hosts.txt" # Merge the old head with the new hosts blacklist

}

function __enable() {
	# Install Host Flash™ hosts list to /etc/hosts

	echo
	# Get su authority
	sudo -v

	# Backup original hosts file before first ever use of Host Flash™ in this system.
	# Only happens if it does not yet exist.
	if test ! -f "${file[hosts]}.hf.original"
	then
		sudo cp "${file[hosts]}" "${file[hosts]}.hf.original"
	fi

	if test -f "${dir[src]}/hosts.txt"
	then
		sudo cp "${file[hosts]}" "${file[hosts]}.hf.backup" # General restore file
		sudo mv -f "${dir[src]}/hosts.txt" "${file[hosts]}" # New hosts file
	else
		message[enable]="$package hosts file not found. Have you built it yet?"
	fi

	# Help the new hosts file take effect.
	__cleandns
	
	sudo -k

}

function __disable() {
	# Remove Host Flash™ hosts list from /etc/hosts

	echo
	# Get su authority
	sudo -v
	
	cp "${file[hosts]}" "${dir[tmp]}/hosts.copy"
	if grep -zPo '# Host.? Flash.? Bad Hosts Block' "${dir[tmp]}/hosts.copy"
	then
		# Remove old HF data, remove HF header remove empty lines.
		grep -zPo '(?s).*# Host.? Flash.? Bad Hosts Block' "${dir[tmp]}/hosts.copy" | head -n -1 | grep -Ev '^[[:space:]]$' > "${dir[tmp]}/hosts.head"
		sudo mv -f "${dir[tmp]}/hosts.head" "${file[hosts]}"
	else
		message[disable]="$package not installed. Nothing to do."
	fi

	# Help the new hosts file take effect.
	__cleandns
	
	sudo -k

}

function __cleandns() {
	# Clean the DNS local servers. We try them all.. just in case.

	flush=(
	'systemd-resolve --flush-caches' # General
	'service network-manager restart' # Debian
	'systemctl restart network.service' # Systemd
	'systemctl restart wicd.service' #  Systemd for WICD
	'systemctl restart NetworkManager.service' # Fedora, Manjaro, Arch using Network Manager
	'service nscd restart' # FreeBSD
	'/etc/init.d/network restart' # RHEL/Centos'
	'/etc/init.d/dns-clean restart' # Mint'
	'/etc/init.d/nscd restart' # other
	'/etc/init.d/networking force-reload' # Other
	'/etc/init.d/dnsmasq restart' # Other
	)
	
	sudo -v

	for i in "${flush[@]}"; do
		printf "${bold}Attempting to flush DNS cache ${normal} using command: $i\n"
		sudo $i
		printf "Do not worry if the above says 'fail'. We only need one success.\n\n"
	done
	
	sudo -k

}

##
# MENUS
##


# Main Menu

function __menu_main() {

	__repaint conf "${file[confcl]}"

	# $1 = instruction

	while true; do

		if test "$?" -eq 0
		then

			case "${conf[mode]}" in

					0)
						mode[0]='MODE: Build Hosts Firewall Only\n'

					;;

					1)
						mode[0]='MODE: Build and Install Hosts Firewall\n'

					;;

			esac

			# Set Menu Options

			unset menu
			menu[1]='List Management (enable or disable repositories)'
			menu[2]='Custom List Management (add or remove rules)\n'

			menu[3]="[${conf[ip]}] - Change redirect IP address\n"

			menu[4]='Change Build/Install Mode\n'

			case "${conf[mode]}" in

				0)
					menu[5]='Build Host Flash™ list but do not install.\n'

				;;

				1)
					menu[5]='Build and Install Host Flash™ list.\n'

				;;

			esac

			menu[6]='Enable Host Flash™ list.'
			menu[7]='Disable Host Flash™ list.'
			case "${conf[mode]}" in

				0)
					menu[8]='Update hosts file with new custom rules but do not enable new hosts file\n'

				;;

				1)
					menu[8]='Update and Enable hosts file with new custom rules\n'

				;;

			esac
			menu[9]='Flush DNS rules\n'

			menu[10]='Restore original hosts file.\n'

			menu[11]="Reset $package configs and files (select in next menu)"

			case "${conf[ess]}" in

				0)
					menu[1000]='Install missing software packages needed by Host Flash™\n'

				;;

			esac

			printf $bold
			printf "${mode[0]}\n"
			printf $normal

			printf "MENU\n\n"
			# printf "INSTRUCTIONS: a) Select lists to install with option 1, b) optionally add custom domains to blacklist or whitelist, c) build the hosts file firewall with option 5, before you d) Enable the newly built hosts file firewall with option 6. Change MODE to Build and Install to set $package to automatically install the hosts file after it is built.\n\n"

			n=1
			for i in "${menu[@]}"; do
				if [ "$i" == '' ]; then
					printf "\n"
				else
					printf "$n) $i\n"
					select[$n]=$n
					let n=n+1
				fi
			done

			printf "\nR) Restart $package\n"
			printf "\n0) Exit\n\n"

			# Notices

			printf $bold

			printf "\nGENERAL INFO\n"
				
			printf $normal

			printf "\n System $package: ${conf[locv]}"
			printf "\n Latest git commit: ${conf[gitv]}\n"
			printf "\n Hosts File Info: Line Count: ${conf[hostc]} | Bytes: ${conf[hosts]} | Timestamp: ${conf[hostt]} | Location: ${bold}${file[hosts]}${normal}\n"

			printf "\nIf the computer crashes during installation lower the number of lists processed or cool your computer then try again.\n"

			printf $bold
				printf "\nChoose Wisely: "
			printf $normal
			read REPLY
		
		else
			REPLY=$1
		fi

		case $REPLY in

		1) # Choose lists to download # When moved to its own menu this will only be [[:num:]]
			__menu_list_management

		;;
		
		2) # Manage custom whitelists and blacklists
			__menu_custom_list_management
			
		;;

		3) # Change redirect IP address

			printf "Current Redirect IP: ${conf[ip]}"
			printf "\nType in new Redirect IP then press Enter:\n\n"
			read ip

			if grep "conf\[ip]=" "${file[conf]}"
			then
				sed -i "s/conf\[ip]='.*'/conf\[ip]='$ip'/g" "${file[conf]}"
			else
				echo -e "conf""[ip]='$ip'" >> "${file[conf]}"
			fi

			__repaint

		;;

		4) # Set Mode

			if grep "conf\[mode]='0'" "${file[conf]}"
			then
				sed -i "s/conf\[mode]='0'/conf\[mode]='1'/g" "${file[conf]}"
				
			elif grep "conf\[mode]='1'" "${file[conf]}"
			then
				sed -i "s/conf\[mode]='1'/conf\[mode]='0'/g" "${file[conf]}"
				
			else
				echo -e "conf""[mode]='1'" >> "${file[conf]}"
			fi

			__repaint

		;;

		5) # Build or Build and Install the Host Flash™ hosts file

			__build
			
			case "${conf[mode]}" in
			
				1)
			
					__enable
					
					if test "${message[enable]}"
					then
						printf "\n${message[enable]}\nPress any key."
						read -a
					fi
					
				;;
				
			esac
			
			__repaint hard

		;;

		6) # Enable Host Flash™ hosts list

			__enable
			__repaint

		;;

		7) # Disable Host Flash™ hosts list

			__disable
			
			if test "${message[disable]}"
			then
				printf "\n${message[disable]}\nPress any key."
				read -a
			fi

			__repaint

		;;

		8) # Update hosts file with new custom rules

			clear

			printf "This next part could take some time.\nLook in ${dir[tmp]} to view activity in realtime.\n\nProcessing...\n"

			cp "${file[hosts]}" "${dir[tmp]}/hosts-temp.txt"
			cat "${dir[tmp]}/hosts-temp.txt" "${file[confbl]}" >> "${dir[tmp]}/hosts.txt"
			
			# Always pass wild through norm too
			__hosts_update "norm" "${dir[tmp]}/hosts.txt" "${file[confwl]}"
			__hosts_update "norm" "${dir[tmp]}/hosts.txt" "${file[confwlw]}"
			__hosts_update "wild" "${dir[tmp]}/hosts.txt" "${file[confwlw]}"

			mv -f "${dir[tmp]}/hosts.txt" "${dir[src]}/hosts.txt"

			case "${conf[mode]}" in
			
				1)
			
					__enable
					
					if test "${message[enable]}"
					then
						printf "\n${message[enable]}\nPress any key."
						read -a
					fi
					
				;;
				
			esac
			
			__repaint hard

		;;
		
		9)
			clear
			__cleandns
			printf "\nPress any key"
			read a
			__repaint
		
		;;

		10) # Restore original hosts list

			if test -f "${file[hosts]}.hf.original"
			then # Restore the backup head from the original hosts file
				sudo mv -f "${file[hosts]}.hf.original" "${file[hosts]}"
			fi

			__repaint

		;;

		11) # Reset Custom Configs

			__menu_reset_confs

			__repaint hard

		;;

		12) # Install software packages necessary to build the package

			case "${conf[ess]}" in
			
				0)

					printf "\nThis will attempt to install the following packages:\n"

					for i in "${essentialpackages[@]}"; do
						printf "$i "
					done

					printf "\nContinue to install them: Yn:\n"
					read a
					
					let n=1
					while true; do
						case $a in

						y|Y)
						
							case $n in
							1)
								echo -e "conf""[ess]='1'" >> "${file[conf]}"
								sudo apt-get update
								let n=n+1
							;;
							esac
							
							for i in "${essentialpackages[@]}"; do
								sudo apt-get build-dep -y -q $i
								sudo apt-get install -y -q --install-suggests $i
							done

							printf "\nPress any key to continue\n"
							read something
							__repaint

						;;

						n|N)

							__repaint

						;;
						
						*)

						esac
						
					done
					
				;;
				
			esac

		;;
		
		[Rr])
			__repaint hard
		;;

		0) # Exit

			exit 0

		;;

		*)

		esac

	done

}


# Sub Menus

function __menu_list_management() {
	# Show and manage host lists
	
	__repaint conf "${file[confcl]}"
	
	while true; do

		printf "${bold}LIST MANAGEMENT${normal}"
		printf "\n\nUpdate list status\n\n"
		
		# Display lists available
		# $listsc # Value discovered during list array auto declares (see above)
		
		n=1
		while [ $n -le $listsc ] ; do
			status="${list[status${n}]}"
			info="${list[info${n}]}"
			printf "$n) [$status] - $info\n"
			print
			let n=n+1
		done
		
		printf "\n0) Return to Main Menu\n"
		
		printf "\nEnter list number to enable [+] or disable [-] then press Enter.\n"
		printf "\nType ${bold}E${normal} to Add, Remove or Edit remote hosts list providers.\n"
		
		read a

		case $a in

			0)
				__menu_main
			;;

			[Ee])
				__menu_remote_list_management

			;;

			*)
				__status $a
				__repaint conf "${file[confcl]}"
			;;

		esac

	done
}

function __menu_remote_list_management() {
	# Add or Remove new remote list providers

	__repaint conf "${file[confcl]}"
	
	while true; do

		printf "${bold}LIST MANAGEMENT: CUSTOM REMOTE SOURCES${normal}"
		printf "\n\nCustom remote list resources\n\n"
		
		# Display custom remote lists available for management
		# $listsc # Value discovered during list array auto declares (see above)

		let n=$listc+1
		while [ $n -le $listsc ] ; do
			status="${list[status${n}]}"
			info="${list[info${n}]}"
			printf "$n) [$status] - $info\n"
			print
			let n=n+1
		done

		printf "\n${bold}A${normal}) to Add a custom remote hosts list provider\n"
		printf "${bold}D${normal}) to Delete a custom remote hosts list provider\n"
		printf "${bold}E${normal}) to Edit a custom remote hosts list provider\n"
		printf "\n0) Return to Main Menu\n"

		read a

		case $a in

			0)
				__menu_main
			;;

			[Aa])

				clear

				printf "\nEnter details for new resource list ${n}.\n\n"
				
				__conf_update 'add' "list[status${n}]='+'" "${file[confcl]}"

				printf "Enter brief list description: "
				read a
				__conf_update 'add' "list[info${n}]='${a}'" "${file[confcl]}"

				printf "\nEnter the download URL e.g https://example.com/download-page.\nDo not include the package/file name or a trailing slash: "
				read a
				__conf_update 'add' "list[src${n}]='${a}'" "${file[confcl]}"

				printf "\nEnter the package name: "
				read a
				__conf_update 'add' "list[file${n}]='${a}'" "${file[confcl]}"

				printf "\nEnter the package type e.g unzip, p7zip, direct or raw: "
				read a
				__conf_update 'add' "list[flag${n}]='${a}'" "${file[confcl]}"

				printf "\nEnter the target file name that contains the hosts data: "
				read a
				__conf_update 'add' "list[target${n}]='${a}'" "${file[confcl]}"

				printf "\nList ${n} added to hosts file repository. $package will restart after you press Enter.\n"
				read a
				
				__repaint hard

			;;

			[Dd])

				printf "\nEnter list number to delete.\n"
				read a

				__conf_update 'remw' "${a}]" "${file[confcl]}"

				printf "\nList ${a} deleted from hosts file repository. $package will restart after you press Enter.\n"
				read a

				__repaint hard
				
			;;

			[Ee])
				# To be implemented
					__repaint hard
			;;

			*)

			;;

		esac

	done
}


function __menu_custom_list_management() {
	# Show and manage host lists
	
	__repaint conf "${file[confcl]}"
	
	while true; do

		printf "${bold}CUSTOM LIST MANAGEMENT${normal}"
		printf "\n\nUpdate list status\n\n"

		# Display custom list options
		unset menu
		menu[1]="Add a host to custom whitelist"
		menu[2]="Add a host to custom wild whitelist"
		menu[3]="Add a host to custom blacklist"
		menu[4]="Remove a host from custom whitelist"
		menu[5]="Remove a host from custom wild whitelist"
		menu[6]="Remove a host from custom blacklist"

		n=1
		for i in "${menu[@]}" ; do
			printf "$n) ${i}\n"
			let n=n+1
		done
		
		printf "\n0) Return to Main Menu\n"
		
		printf "\nEnter option number then press Enter.\n"
		
		read a

		case $a in

			0)
				__menu_main
			;;

			1) # Add to custom whitelist

				printf "Custom whitelist is located at ${file[confwl]}\n\n"
				printf "Type in a host to add then press Enter. Press 0 to exit:\n\n"
				read a
				
				case $a in
					0)
						__repaint '__menu_custom_list_management' # Effectively 'Return here'
					;;
					
					*)
						__conf_update 'add' "$a" "${file[confwl]}"
						__repaint '__menu_custom_list_management' # Effectively 'Return here'
					;;
				esac

			;;

			2) # Add to custom wild whitelist

				printf "Custom wild whitelist is located at ${file[confwlw]}\n\n"
				printf "Type in a host to add then press Enter. Press 0 to exit:\n\n"
				read a

				case $a in
					0)
						__repaint '__menu_custom_list_management' # Effectively 'Return here'
					;;
					
					*)
						__conf_update 'add' "$a" "${file[confwlw]}" # Add host to wild whitelist
						__repaint '__menu_custom_list_management' # Effectively 'Return here'
					;;
				esac

			;;

			3) # Add to custom blacklist

				printf "Custom blacklist is located at ${file[confbl]}\n\n"
				printf "Type in a host to add then press Enter. Press 0 to exit:\n\n"
				read a

				case $a in
					0)
						__repaint '__menu_custom_list_management' # Effectively 'Return here'
					;;
					
					*)
						__conf_update 'add' "$a" "${file[confbl]}"
						__repaint '__menu_custom_list_management' # Effectively 'Return here'
					;;
				esac

			;;

			4) # Remove from custom whitelist

				printf "Custom whitelist is located at ${file[confwl]}\n\n"
				printf "Type in a host to add then press Enter. Press 0 to exit:\n\n"
				read a

				case $a in
					0)
						__repaint '__menu_custom_list_management' # Effectively 'Return here'
					;;
					
					*)
						__conf_update 'rem' "$a" "${file[confwl]}"
						__repaint '__menu_custom_list_management' # Effectively 'Return here'
					;;
				esac

			;;

			5) # Remove from custom wild whitelist

				printf "Custom wild whitelist is located at ${file[confwlw]}\n\n"
				printf "Type in a host to add then press Enter. Press 0 to exit:\n\n"
				read a

				case $a in
					0)
						__repaint '__menu_custom_list_management' # Effectively 'Return here'
					;;
					
					*)
						__conf_update 'rem' "$a" "${file[confwlw]}"
						__repaint '__menu_custom_list_management' # Effectively 'Return here'
					;;
				esac

			;;

			6) # Remove from custom blacklist

				printf "Custom blacklist is located at ${file[confbl]}\n\n"
				printf "Type in a host to add then press Enter. Press 0 to exit:\n\n"
				read a

				case $a in
					0)
						__repaint '__menu_custom_list_management' # Effectively 'Return here'
					;;
					
					*)
						__conf_update 'rem' "$a" "${file[confbl]}"
						__repaint '__menu_custom_list_management' # Effectively 'Return here'
					;;
				esac

			;;

			*)


			;;

		esac

	done
}

function __menu_reset_confs() {

	__repaint conf "${file[confcl]}"

	while true; do

		printf "${bold}CUSTOM CONFS MANAGEMENT${normal}"
		printf "\n\nReset custom lists and configurations\n\n"

		# Display menu
		unset menu
		menu[1]="Reset general configurations to their default values"
		menu[2]="Delete custom host file repository lists"
		menu[3]="Delete custom whitelist"
		menu[4]="Delete custom whitelist wild"
		menu[5]="Delete custom blacklist"
		menu[6]="Delete log of removed hosts"
		menu[7]="Delete general log"
		menu[8]="Delete debug log"

		m=1
		while [ $m -le ${#menu[@]} ] ; do
			printf "$m) ${menu[$m]}\n"
			print
			let m=m+1
		done
		
		printf "\n0) Return to Main Menu\n"
		
		printf "\nEnter item number to action then press Enter.\n"
		
		read a

		case $a in

			0)
				__menu_main
			;;

			1) # Reset confs[]
				__conf_delete "${file[conf]}" "$package custom configuration"

			;;

			2) # Delete custom host lists
				__conf_delete "${file[confcl]}" "Custom host file repositories"

			;;

			3) # Delete custom whitelist
				__conf_delete "${file[confwl]}" "custom whitelist"
			;;

			4) # Delete custom whitelist wild
				__conf_delete "${file[confwlw]}" "custom whitelist wild"

			;;

			5) # Delete custom blacklist
				__conf_delete "${file[confbl]}" "custom blacklist"

			;;

			6)
				__conf_delete "${file[confr]}" "removed hosts log"

			;;

			7)
			__conf_delete "${file[log]}" "removed hosts log"

			;;

			8)

			;;

			*)
				__repaint conf "${file[confcl]}"
			;;

		esac

	done

	__repaint conf "${file[confcl]}"

}


## Launch

function __launch() {
	# launch terminal

	terminal=( konsole gnome-terminal x-terminal-emulator xdg-terminal terminator urxvt rxvt Eterm aterm roxterm xfce4-terminal termite lxterminal xterm )
	for i in ${terminal[@]}; do
		if command -v $i > /dev/null 2>&1; then
			exec $i -e "$0"
			# break
		else
			printf "\nUnable to automatically determine the correct terminal program to run e.g Console or Konsole. Please run this $package from the command line.\n"
			read something
			exit 1
		fi
	done
}

## Debug Flags

case "${debug}" in

	1)

		#exec 3>&1 4>&2
		#trap 'exec 2>&4 1>&3' 0 1 2 3
		#exec 2>&1 >> "${file[log]}"
		exec 2>> "${file[debug]}"
	;;
	
esac

## Boot
__run "$@" # Loops back to the start. The script is read by BASH then __run is run. This ensures all functions are read into memory before anything happens.

# Exit is at end of __run()

# FOR DEBUGGING

# declare -p
